---
title: თავი - Bugs and Errors - JavaScript 2023F
description: სასწავლო რესურსები
---

### ლექცია 9

<iframe
  width="560"
  height="315"
  src="https://www.youtube.com/embed/gkJCYFCG-J0?si=xHZt4aVhi7LXUjdH"
  title="YouTube video player"
  frameBorder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
  allowFullScreen
></iframe>

### პრაქტიკული სემინარები

<Card>
  <PinCodeProtectedContent>
    <Locked>
      ეს კონტენტი განკუთვნილია აქტიური სტუდენტებისთვის. პინ კოდი მოითხოვეთ
      მენტორთან!
    </Locked>
    <Unlocked>
      - ორშაბათი: https://youtu.be/znkPbmFVPLI 
      - ოთხშაბათი: https://youtu.be/81Qs_nv022Q 
      - პარასკევი: https://youtu.be/_uJUMWG26Do
    </Unlocked>
  </PinCodeProtectedContent>
</Card>

### რესუსრსები

- წიგნი: [Eloquent JavaScript](https://eloquentjavascript.net/)
- ედიტორი: [programiz.com](https://www.programiz.com/javascript/online-compiler/)

### წასაკითხი

- წაიკითხეთ თავი VIII - [Bugs and Errors](https://eloquentjavascript.net/08_error.html)

### სავარჯიშოები

#### Retry
Say you have a function primitiveMultiply that in 20 percent of cases multiplies two numbers and in the other 80 percent of cases raises an exception of type MultiplicatorUnitFailure. Write a function that wraps this clunky function and just keeps trying until a call succeeds, after which it returns the result.

Make sure you handle only the exceptions you are trying to handle.
```shell
class MultiplicatorUnitFailure extends Error {}

function primitiveMultiply(a, b) {
  if (Math.random() < 0.2) {
    return a * b;
  } else {
    throw new MultiplicatorUnitFailure("Klunk");
  }
}

function reliableMultiply(a, b) {
  // Your code here.
}

console.log(reliableMultiply(8, 8));
// → 64
```

#### The locked box
Consider the following (rather contrived) object:
```shell
const box = {
  locked: true,
  unlock() { this.locked = false; },
  lock() { this.locked = true;  },
  _content: [],
  get content() {
    if (this.locked) throw new Error("Locked!");
    return this._content;
  }
};
```
It is a box with a lock. There is an array in the box, but you can get at it only when the box is unlocked. Directly accessing the private _content property is forbidden.

Write a function called withBoxUnlocked that takes a function value as argument, unlocks the box, runs the function, and then ensures that the box is locked again before returning, regardless of whether the argument function returned normally or threw an exception.

```shell
const box = {
  locked: true,
  unlock() { this.locked = false; },
  lock() { this.locked = true;  },
  _content: [],
  get content() {
    if (this.locked) throw new Error("Locked!");
    return this._content;
  }
};

function withBoxUnlocked(body) {
  // Your code here.
}

withBoxUnlocked(function() {
  box.content.push("gold piece");
});

try {
  withBoxUnlocked(function() {
    throw new Error("Pirates on the horizon! Abort!");
  });
} catch (e) {
  console.log("Error raised: " + e);
}
console.log(box.locked);
// → true
```

For extra points, make sure that if you call withBoxUnlocked when the box is already unlocked, the box stays unlocked.
